### ISSUE TITLE
How to actually display the PDF assets ?

### ISSUE THREAD

**Issue by adadgio** [SyslogicNL/pdf-extractor#12]
The question is in the title... ;-).

I have tested a few documents with the default Box `viewer.js` but the PDF do not render although this library is presented as a replacement for the legacy BoxView.

**Comment by Hikariii** [comment]
We've personally never used the viewer.js from Box, just the raw data (html and png/svg).
We created our own viewer around this data.
The `viewer.js` was very limited, custom branded, and not useful in our own application.

I never really took a good look at the `viewer.js` code but I do not think it was made to view raw data served from your own webserver. I'm pretty sure it just uses the box api.

**Comment by Hikariii** [comment]
By far the best way of rendering pdf's in the browser (box viewer functionality) is using https://github.com/mozilla/pdf.js/ directly

**Comment by adadgio** [comment]
I have made this alternative (for a server build from your solution but it should work straight out of the box) : https://github.com/adadgio/paperview-js
